---
name: deployed
on: page_build
jobs:
    test-deployed-page:
        if: github.event.context == 'github/pages' && github.event.state == 'success'
        runs-on: ubuntu-latest
        steps:
            - run: echo "gh-pages ðŸ“‘ built successfully âœ…"

            - name: check that page is reachable
              run: curl -s https://big-map.github.io/big-map-registry/

            - uses: actions/setup-node@v3
              with:
                  node-version: '12'

            - name: install broken link checker
              run: |
                  npm install broken-link-checker -g

            - name: check for broken links
              run: |
                  blc https://big-map.github.io/big-map-registry/ -ro
